export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const RESET = 'RESET'
export const MULTIPLE3 = 'MULTIPLE3'
export const ADD_EVENT = 'ADD_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'
export const ALLDELI_EVENT = 'ALLDELI_EVENT'